# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradient_thresholds_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call('_PseudoMLE_gradient_thresholds_pseudolikelihood', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories)
}

gradient_thresholds_pseudoposterior <- function(interactions, thresholds, observations, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call('_PseudoMLE_gradient_thresholds_pseudoposterior', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories, threshold_alpha, threshold_beta)
}

gradient_interactions_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call('_PseudoMLE_gradient_interactions_pseudolikelihood', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories)
}

gradient_interactions_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var) {
    .Call('_PseudoMLE_gradient_interactions_pseudoposterior_normal', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories, interaction_var)
}

gradient_interactions_pseudoposterior_cauchy <- function(interactions, thresholds, observations, no_categories, cauchy_scale) {
    .Call('_PseudoMLE_gradient_interactions_pseudoposterior_cauchy', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories, cauchy_scale)
}

hessian_thresholds_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call('_PseudoMLE_hessian_thresholds_pseudolikelihood', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories)
}

hessian_thresholds_pseudoposterior <- function(interactions, thresholds, observations, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call('_PseudoMLE_hessian_thresholds_pseudoposterior', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories, threshold_alpha, threshold_beta)
}

hessian_interactions_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call('_PseudoMLE_hessian_interactions_pseudolikelihood', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories)
}

hessian_interactions_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var) {
    .Call('_PseudoMLE_hessian_interactions_pseudoposterior_normal', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories, interaction_var)
}

hessian_interactions_pseudoposterior_cauchy <- function(interactions, thresholds, observations, no_categories, cauchy_scale) {
    .Call('_PseudoMLE_hessian_interactions_pseudoposterior_cauchy', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories, cauchy_scale)
}

hessian_crossparameters <- function(interactions, thresholds, observations, no_categories) {
    .Call('_PseudoMLE_hessian_crossparameters', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories)
}

log_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call('_PseudoMLE_log_pseudolikelihood', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories)
}

log_unnormalized_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call('_PseudoMLE_log_unnormalized_pseudoposterior_normal', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories, interaction_var, threshold_alpha, threshold_beta)
}

log_unnormalized_pseudoposterior_cauchy <- function(interactions, thresholds, observations, cauchy_scale, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call('_PseudoMLE_log_unnormalized_pseudoposterior_cauchy', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, cauchy_scale, no_categories, threshold_alpha, threshold_beta)
}

emvs_log_unnormalized_pseudoposterior <- function(interactions, thresholds, observations, no_categories, xi, slab_var, theta = 0.5, hierarchical = FALSE, indicator_alpha = 1.0, indicator_beta = 1.0, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call('_PseudoMLE_emvs_log_unnormalized_pseudoposterior', PACKAGE = 'PseudoMLE', interactions, thresholds, observations, no_categories, xi, slab_var, theta, hierarchical, indicator_alpha, indicator_beta, threshold_alpha, threshold_beta)
}

